//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Enterprise.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResetEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResetEmail() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Enterprise.Web.Resources.AccountResetEmail", typeof(AccountResetEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Code 的本地化字符串。
        /// </summary>
        public static string CodeField {
            get {
                return ResourceManager.GetString("CodeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the verify code 的本地化字符串。
        /// </summary>
        public static string CodePlaceholder {
            get {
                return ResourceManager.GetString("CodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This email is bind in other account 的本地化字符串。
        /// </summary>
        public static string EmailBindByOtherAccount {
            get {
                return ResourceManager.GetString("EmailBindByOtherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The email you input is not match what you set 的本地化字符串。
        /// </summary>
        public static string EmailNotMatch {
            get {
                return ResourceManager.GetString("EmailNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New email can&apos;t be same as the original 的本地化字符串。
        /// </summary>
        public static string EmailSameAsOriginal {
            get {
                return ResourceManager.GetString("EmailSameAsOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify code of FiiiLab 的本地化字符串。
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your code is {0}, which is used of checking new email 的本地化字符串。
        /// </summary>
        public static string NewEmailContent {
            get {
                return ResourceManager.GetString("NewEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Email 的本地化字符串。
        /// </summary>
        public static string NewEmailField {
            get {
                return ResourceManager.GetString("NewEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the original email 的本地化字符串。
        /// </summary>
        public static string NewEmailPlaceholder {
            get {
                return ResourceManager.GetString("NewEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your code is {0}, which is used of checking original email 的本地化字符串。
        /// </summary>
        public static string OriginalEmailContent {
            get {
                return ResourceManager.GetString("OriginalEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Email 的本地化字符串。
        /// </summary>
        public static string OriginalEmailField {
            get {
                return ResourceManager.GetString("OriginalEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the original email 的本地化字符串。
        /// </summary>
        public static string OriginalEmailPlaceholder {
            get {
                return ResourceManager.GetString("OriginalEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Information 的本地化字符串。
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Email 的本地化字符串。
        /// </summary>
        public static string SubPageName {
            get {
                return ResourceManager.GetString("SubPageName", resourceCulture);
            }
        }
    }
}
