//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Enterprise.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountLogin() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Enterprise.Web.Resources.AccountLogin", typeof(AccountLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account disabled 的本地化字符串。
        /// </summary>
        public static string AccountDisabed {
            get {
                return ResourceManager.GetString("AccountDisabed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget the account? 的本地化字符串。
        /// </summary>
        public static string ForgetAccount {
            get {
                return ResourceManager.GetString("ForgetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget the password? 的本地化字符串。
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed 的本地化字符串。
        /// </summary>
        public static string Loginfailed {
            get {
                return ResourceManager.GetString("Loginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant ID 的本地化字符串。
        /// </summary>
        public static string MerchantIDField {
            get {
                return ResourceManager.GetString("MerchantIDField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account is not exist 的本地化字符串。
        /// </summary>
        public static string MerchantIdNotExist {
            get {
                return ResourceManager.GetString("MerchantIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the Merchant ID 的本地化字符串。
        /// </summary>
        public static string MerchantIDPlaceholder {
            get {
                return ResourceManager.GetString("MerchantIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account login 的本地化字符串。
        /// </summary>
        public static string PageFunction {
            get {
                return ResourceManager.GetString("PageFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant Center 的本地化字符串。
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the password 的本地化字符串。
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
    }
}
