//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Enterprise.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResetPsw {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResetPsw() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Enterprise.Web.Resources.AccountResetPsw", typeof(AccountResetPsw).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm New Password 的本地化字符串。
        /// </summary>
        public static string ConfirmNewPasswordField {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm the new password 的本地化字符串。
        /// </summary>
        public static string ConfirmNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm passowrd do not match the new passowrd 的本地化字符串。
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        public static string NewPasswordField {
            get {
                return ResourceManager.GetString("NewPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the new password 的本地化字符串。
        /// </summary>
        public static string NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old Password 的本地化字符串。
        /// </summary>
        public static string OldPasswordField {
            get {
                return ResourceManager.GetString("OldPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the old password 的本地化字符串。
        /// </summary>
        public static string OldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("OldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Information 的本地化字符串。
        /// </summary>
        public static string Pagename {
            get {
                return ResourceManager.GetString("Pagename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Password 的本地化字符串。
        /// </summary>
        public static string SubPagename {
            get {
                return ResourceManager.GetString("SubPagename", resourceCulture);
            }
        }
    }
}
