//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Enterprise.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Enterprise.Web.Resources.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email code verify failded more times, please try it tommorow 的本地化字符串。
        /// </summary>
        public static string EmailCodeIncorrectMoreTimes {
            get {
                return ResourceManager.GetString("EmailCodeIncorrectMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} format is incorrect 的本地化字符串。
        /// </summary>
        public static string FieldFormatError {
            get {
                return ResourceManager.GetString("FieldFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequent option, try it later 的本地化字符串。
        /// </summary>
        public static string OptionTooFrequent {
            get {
                return ResourceManager.GetString("OptionTooFrequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password verify failded more times，please try it after {0} minutes 的本地化字符串。
        /// </summary>
        public static string PasswordIncorrectMoreTimes {
            get {
                return ResourceManager.GetString("PasswordIncorrectMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password incorrect,{0} times left 的本地化字符串。
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save failed 的本地化字符串。
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send code 的本地化字符串。
        /// </summary>
        public static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} need at least {2} character 的本地化字符串。
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System error, please try it later 的本地化字符串。
        /// </summary>
        public static string SystemException {
            get {
                return ResourceManager.GetString("SystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify code incorrect 的本地化字符串。
        /// </summary>
        public static string VerifyCodeIncorrect {
            get {
                return ResourceManager.GetString("VerifyCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant Center 的本地化字符串。
        /// </summary>
        public static string WebName {
            get {
                return ResourceManager.GetString("WebName", resourceCulture);
            }
        }
    }
}
