//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Enterprise.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewsFlash {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsFlash() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Enterprise.Web.Resources.NewsFlash", typeof(NewsFlash).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash Management 的本地化字符串。
        /// </summary>
        internal static string FlashPageName {
            get {
                return ResourceManager.GetString("FlashPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News Flash/Publish News Flash 的本地化字符串。
        /// </summary>
        internal static string FlashTitle {
            get {
                return ResourceManager.GetString("FlashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Negative Num 的本地化字符串。
        /// </summary>
        internal static string NegativeNumber {
            get {
                return ResourceManager.GetString("NegativeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewsFlashStatus 的本地化字符串。
        /// </summary>
        internal static string NewsFlashStatus {
            get {
                return ResourceManager.GetString("NewsFlashStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Positive Num 的本地化字符串。
        /// </summary>
        internal static string PositiveNumber {
            get {
                return ResourceManager.GetString("PositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published 的本地化字符串。
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish Flash 的本地化字符串。
        /// </summary>
        internal static string PublishFlash {
            get {
                return ResourceManager.GetString("PublishFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReleaseFlash 的本地化字符串。
        /// </summary>
        internal static string ReleaseFlash {
            get {
                return ResourceManager.GetString("ReleaseFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Drafts 的本地化字符串。
        /// </summary>
        internal static string SaveDrafts {
            get {
                return ResourceManager.GetString("SaveDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpublished 的本地化字符串。
        /// </summary>
        internal static string Unpublished {
            get {
                return ResourceManager.GetString("Unpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Version 的本地化字符串。
        /// </summary>
        internal static string VersionCN {
            get {
                return ResourceManager.GetString("VersionCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English Version 的本地化字符串。
        /// </summary>
        internal static string VersionEN {
            get {
                return ResourceManager.GetString("VersionEN", resourceCulture);
            }
        }
    }
}
