//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiPay.Enterprise.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class News {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal News() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiPay.Enterprise.Web.Resources.News", typeof(News).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cover Plan 的本地化字符串。
        /// </summary>
        internal static string CoverPlan {
            get {
                return ResourceManager.GetString("CoverPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload JPG/PNG file with size of 316x226PX (width/height ratio of 7:5), suggest below 1M, maximum 1. 的本地化字符串。
        /// </summary>
        internal static string CoverPlanRequire {
            get {
                return ResourceManager.GetString("CoverPlanRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Introduction 的本地化字符串。
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keywords1 的本地化字符串。
        /// </summary>
        internal static string Keywords1 {
            get {
                return ResourceManager.GetString("Keywords1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keywords2 的本地化字符串。
        /// </summary>
        internal static string Keywords2 {
            get {
                return ResourceManager.GetString("Keywords2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News Management 的本地化字符串。
        /// </summary>
        internal static string NewsManagement {
            get {
                return ResourceManager.GetString("NewsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewsStatus 的本地化字符串。
        /// </summary>
        internal static string NewsStatus {
            get {
                return ResourceManager.GetString("NewsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News/Publish News 的本地化字符串。
        /// </summary>
        internal static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pageviews 的本地化字符串。
        /// </summary>
        internal static string Pageviews {
            get {
                return ResourceManager.GetString("Pageviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published 的本地化字符串。
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publisher 的本地化字符串。
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish News 的本地化字符串。
        /// </summary>
        internal static string PublishNews {
            get {
                return ResourceManager.GetString("PublishNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReleaseNews 的本地化字符串。
        /// </summary>
        internal static string ReleaseNews {
            get {
                return ResourceManager.GetString("ReleaseNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Drafts 的本地化字符串。
        /// </summary>
        internal static string SaveDrafts {
            get {
                return ResourceManager.GetString("SaveDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Section 的本地化字符串。
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CN Name 的本地化字符串。
        /// </summary>
        internal static string SectionCNName {
            get {
                return ResourceManager.GetString("SectionCNName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EN Name 的本地化字符串。
        /// </summary>
        internal static string SectionENName {
            get {
                return ResourceManager.GetString("SectionENName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort 的本地化字符串。
        /// </summary>
        internal static string SectionSort {
            get {
                return ResourceManager.GetString("SectionSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string SectionSubmit {
            get {
                return ResourceManager.GetString("SectionSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Section/Add Section 的本地化字符串。
        /// </summary>
        internal static string SectionTitle {
            get {
                return ResourceManager.GetString("SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpublished 的本地化字符串。
        /// </summary>
        internal static string Unpublished {
            get {
                return ResourceManager.GetString("Unpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Version 的本地化字符串。
        /// </summary>
        internal static string VersionCN {
            get {
                return ResourceManager.GetString("VersionCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English Version 的本地化字符串。
        /// </summary>
        internal static string VersionEN {
            get {
                return ResourceManager.GetString("VersionEN", resourceCulture);
            }
        }
    }
}
